export default {
  id: 'dark',
  name: '暗黑酷炫',
  emoji: '🌑',
  vars: {
    '--body-bg': '#1a1a2e',
    '--body-padding': '20px',
    '--text-color': '#c8d6e5',
    '--text-size': '15px',
    '--line-height': '1.8',
    '--font-family': '"JetBrains Mono", "Fira Code", Consolas, "PingFang SC", "Microsoft YaHei", monospace',
    '--primary': '#00d4ff',
    '--h1-size': '24px',
    '--h1-color': '#00d4ff',
    '--h1-weight': '700',
    '--h1-border-bottom': '1px solid #00d4ff',
    '--h1-padding-bottom': '10px',
    '--h2-size': '20px',
    '--h2-color': '#00d4ff',
    '--h2-weight': '700',
    '--h2-border-left': '4px solid #00d4ff',
    '--h2-padding-left': '12px',
    '--h3-size': '17px',
    '--h3-color': '#7ec8e3',
    '--h3-weight': '700',
    '--strong-color': '#00d4ff',
    '--em-color': '#7ec8e3',
    '--a-color': '#00d4ff',
    '--blockquote-bg': '#16213e',
    '--blockquote-border': '#00d4ff',
    '--blockquote-color': '#8a9bb0',
    '--code-bg': '#0f3460',
    '--code-color': '#00d4ff',
    '--code-border': '#1a4a8a',
    '--pre-bg': '#0d1117',
    '--pre-color': '#c9d1d9',
    '--table-header-bg': '#0f3460',
    '--table-header-color': '#00d4ff',
    '--table-border': '#1e3a5f',
    '--table-row-even': '#16213e',
    '--hr-color': '#1e3a5f',
  }
}
