export default {
  id: 'green-forest',
  name: '绿色森林',
  emoji: '🌿',
  vars: {
    '--body-bg': '#f0f7f0',
    '--body-padding': '20px',
    '--text-color': '#2d4a2d',
    '--text-size': '15px',
    '--line-height': '1.85',
    '--font-family': '-apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    '--primary': '#4caf50',
    '--h1-size': '24px',
    '--h1-color': '#1b5e20',
    '--h1-weight': '700',
    '--h1-border-bottom': '2px solid #4caf50',
    '--h1-padding-bottom': '10px',
    '--h2-size': '20px',
    '--h2-color': '#1b5e20',
    '--h2-weight': '700',
    '--h2-border-left': '4px solid #4caf50',
    '--h2-padding-left': '12px',
    '--h3-size': '17px',
    '--h3-color': '#2e7d32',
    '--h3-weight': '700',
    '--strong-color': '#2e7d32',
    '--em-color': '#558b2f',
    '--a-color': '#2e7d32',
    '--blockquote-bg': '#e8f5e9',
    '--blockquote-border': '#4caf50',
    '--blockquote-color': '#33691e',
    '--code-bg': '#f1f8e9',
    '--code-color': '#1b5e20',
    '--code-border': '#c5e1a5',
    '--pre-bg': '#1b3a20',
    '--pre-color': '#c8e6c9',
    '--table-header-bg': '#4caf50',
    '--table-header-color': '#ffffff',
    '--table-border': '#c5e1a5',
    '--table-row-even': '#e8f5e9',
    '--hr-color': '#c5e1a5',
  }
}
