export default {
  id: 'literary',
  name: '文艺清新',
  emoji: '🌸',
  vars: {
    '--body-bg': '#fdf6f0',
    '--body-padding': '20px',
    '--text-color': '#5c4a3a',
    '--text-size': '15px',
    '--line-height': '1.9',
    '--font-family': 'Georgia, "Times New Roman", "PingFang SC", "STSong", "SimSun", serif',
    '--primary': '#d4956a',
    '--h1-size': '24px',
    '--h1-color': '#8b5e3c',
    '--h1-weight': '700',
    '--h1-border-bottom': '1px solid #d4956a',
    '--h1-padding-bottom': '10px',
    '--h2-size': '20px',
    '--h2-color': '#8b5e3c',
    '--h2-weight': '700',
    '--h2-border-left': '4px solid #d4a574',
    '--h2-padding-left': '12px',
    '--h3-size': '17px',
    '--h3-color': '#7a5040',
    '--h3-weight': '700',
    '--strong-color': '#c0713a',
    '--em-color': '#a0785a',
    '--a-color': '#c0713a',
    '--blockquote-bg': '#fdf0e6',
    '--blockquote-border': '#d4a574',
    '--blockquote-color': '#8b6550',
    '--code-bg': '#fdf0e8',
    '--code-color': '#c0713a',
    '--code-border': '#e8c9aa',
    '--pre-bg': '#f5e6d8',
    '--pre-color': '#5c4a3a',
    '--table-header-bg': '#d4956a',
    '--table-header-color': '#ffffff',
    '--table-border': '#e8c9aa',
    '--table-row-even': '#fdf0e6',
    '--hr-color': '#e8c9aa',
  }
}
