export default {
  id: 'tech-blue',
  name: '科技蓝',
  emoji: '🔵',
  vars: {
    '--body-bg': '#f0f7ff',
    '--body-padding': '20px',
    '--text-color': '#1a2a4a',
    '--text-size': '15px',
    '--line-height': '1.8',
    '--font-family': '"Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
    '--primary': '#1e88e5',
    '--h1-size': '24px',
    '--h1-color': '#0d47a1',
    '--h1-weight': '700',
    '--h1-border-bottom': '2px solid #1e88e5',
    '--h1-padding-bottom': '10px',
    '--h2-size': '20px',
    '--h2-color': '#0d47a1',
    '--h2-weight': '700',
    '--h2-border-left': '4px solid #1e88e5',
    '--h2-padding-left': '12px',
    '--h3-size': '17px',
    '--h3-color': '#1565c0',
    '--h3-weight': '700',
    '--strong-color': '#1565c0',
    '--em-color': '#1e88e5',
    '--a-color': '#1e88e5',
    '--blockquote-bg': '#e3f2fd',
    '--blockquote-border': '#1e88e5',
    '--blockquote-color': '#1565c0',
    '--code-bg': '#e8f4fd',
    '--code-color': '#0d47a1',
    '--code-border': '#bbdefb',
    '--pre-bg': '#1a2a4a',
    '--pre-color': '#e3f2fd',
    '--table-header-bg': '#1e88e5',
    '--table-header-color': '#ffffff',
    '--table-border': '#bbdefb',
    '--table-row-even': '#e3f2fd',
    '--hr-color': '#90caf9',
  }
}
